apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes-app-deployment
  namespace: dep-svc-ingress-namespace
  labels:
    app: django-notes-app
    env: UAT
spec:
  replicas: 3

  selector:
    matchLabels:
      app: django-notes-app
      env: UAT

  template:
    metadata:
      labels:
        app: django-notes-app
        env: UAT

    spec:
      containers:
      - name: django-notes-app
        image: django-notes-app:v1
        ports:
        - containerPort: 8000
        command: ["python3"]
        args: ["manage.py", "runserver", "0.0.0.0:8000", "--noreload"]

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
