apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demoapp-uat
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
