apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: dep-svc-ingress-namespace
  labels:
    app: nginx
    env: UAT

spec:
  type: ClusterIP

  selector:
    app: nginx
    env: UAT

  ports:
  - port: 80
    targetPort: 80