apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: demoapp-uat
  labels:
    app: app-service
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 5678
  type: ClusterIP