apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: learning
  labels:
    app: nginx
    tier: frontend
    env: uat
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      env: uat
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        env: uat
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        
    