apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: learning
  labels:
    app: nginx
  annotations:
    owner: "karishma"
    environment: "uat"
    build-version: "latest"
    description: "Pod will not allocate as every nodes has a taint"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "250Mi"
        ports:
        - containerPort: 80
      tolerations:
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
