apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-developer-role
  namespace: frontend-dev
  labels:
    team: developer
    environment: frontend-dev
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - list
      - get
      - update
      - watch