---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resouce-deploy
  namespace: default
  labels:
    app: resouce-pod
  uid: 8aefada0-c5f4-4571-8862-cf72ba5c2fbc
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: resouce-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resouce-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "512Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
