apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-affinity-deployment
  namespace: learning
  labels:
    app: redis-affinity
  annotations:
    owner: "karishma"
    environment: "uat"
    build-version: "latest"
    description: "deployment description"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-affinity
  template:
    metadata:
      labels:
        app: redis-affinity
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "250Mi"
        ports:
        - containerPort: 6379
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: Exists