kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-dev-read-only-rb
  namespace: dev
subjects:
- kind: Group
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-read-only
  apiGroup: rbac.authorization.k8s.io
