apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: nginx-ingress
  namespace: dep-svc-ingress-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx

  rules:
  - host: nginx.local

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: nginx-service
            port:
              number: 80

      - path: /app(/|$)(.*)
        pathType: ImplementationSpecific

        backend:
          service:
            name: django-notes-app-service
            port:
              number: 80
