# Creating the namespace: dev, qa and prod in kind cluster
kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    env: dev

---
kind: Namespace
apiVersion: v1
metadata:
  name: qa
  labels:
    env: qa

---
kind: Namespace
apiVersion: v1
metadata:
  name: prod
  labels:
    env: prod

